// Command generate-rules-doc generates docs/rules.md, the reference of all rule IDs, from the rule
// registry of the jactionlint package. With -check it only verifies that the file is up to date.
package main

import (
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/jdx/jactionlint/v2"
)

func levelText(s jactionlint.Severity) string {
	return s.String()
}

func profileText(p jactionlint.Profile) string {
	if p == "" {
		return "only when configured"
	}
	return string(p)
}

// ruleProfileText describes when a rule is enabled. Online rules do not follow a profile: they run
// when the online checks are on.
func ruleProfileText(r jactionlint.RuleInfo) string {
	if r.Online {
		return "only with `-online`"
	}
	return profileText(r.Profile)
}

func yesNo(b bool) string {
	if b {
		return "yes"
	}
	return "no"
}

func generate(w io.Writer) error {
	var b strings.Builder
	b.WriteString(`<!-- Generated by scripts/generate-rules-doc from the rule registry. Do not edit by hand: run "go run ./scripts/generate-rules-doc". -->

# Rules

Every diagnostic of jactionlint has a stable ID such as ` + "`unpinned-uses`" + `. IDs are never renamed or reused, so they are safe to write in
[the configuration](./config.md), in [ignore comments](./usage.md#ignore-some-errors) and in CI annotations. The ID of a
finding is in the ` + "`id`" + ` field of ` + "`-format json`" + `, in the ` + "`ruleId`" + ` of ` + "`-format sarif`" + ` and in the output of ` + "`-rule-ids`" + `.

Each rule has:

- a **group**: ` + "`correctness`" + ` (mistakes which make a workflow fail or misbehave), ` + "`security`" + ` (insecure constructs), ` + "`policy`" + `
  (good practices which are not mistakes by themselves) or ` + "`style`" + `.
- a **default level**: ` + "`error`" + `, ` + "`warn`" + ` or ` + "`info`" + `. Only errors make jactionlint exit with status 1 unless ` + "`-strict-exit`" + ` is given.
- a **profile**: the first [profile](./config.md#profiles) which enables the rule. There are three, and each includes the rules
  of the one before it: ` + "`correctness`" + ` (what actionlint checks and the bug detectors of jactionlint), ` + "`default`" + ` (adds the
  security posture and policy rules, and is used when no profile is configured) and ` + "`pedantic`" + ` (adds the noisy and opinionated
  rules). Rules which no profile enables run only when the configuration turns them on, and the rules marked "only with
  ` + "`-online`" + `" run with that flag whatever the profile is. The profile comes from the ` + "`profile`" + ` key of the configuration or the
  ` + "`-profile`" + ` flag.
- a **pedantic option**: a few audits report their noisier findings too when the option ` + "`pedantic`" + ` is true. It is true under
  the ` + "`pedantic`" + ` profile and false otherwise, and ` + "`rules: {<id>: {pedantic: true}}`" + ` turns it on for one audit.

The rules of the security, policy and style groups do not look at a job or a step whose ` + "`if:`" + ` is the literal ` + "`false`" + `, because it
never runs. The rules of the correctness group still do: a mistake in it breaks the file whether it runs or not.

` + "```yaml" + `
# .github/jactionlint.yaml
profile: pedantic
rules:
  unpinned-uses: warn # lower the level
  require-shell: off # turn a rule off
` + "```" + `

| ID | Group | Default level | Profile |
| --- | --- | --- | --- |
`)
	rules := jactionlint.Rules()
	for _, r := range rules {
		fmt.Fprintf(&b, "| [%s](#%s) | %s | %s | %s |\n", r.ID, r.ID, r.Group, levelText(r.DefaultLevel), ruleProfileText(r))
	}
	b.WriteString("\n")

	for _, r := range rules {
		fmt.Fprintf(&b, "## %s\n\n%s\n\n", r.ID, r.Summary)
		fmt.Fprintf(&b, "- Group: %s\n- Default level: %s\n- Profile: %s\n", r.Group, levelText(r.DefaultLevel), ruleProfileText(r))
		if r.Online {
			b.WriteString("- Needs network access: yes (only with `-online`)\n")
		}
		if r.Fixable {
			fmt.Fprintf(&b, "- Fixable: %s\n", yesNo(r.Fixable))
		}
		for _, o := range r.Options {
			def := "no default"
			if m, ok := o.Default.(map[string]string); ok && len(m) == 0 {
				def = "default empty"
			} else if o.Default != nil {
				def = fmt.Sprintf("default %v", o.Default)
			} else if o.Kind == jactionlint.RuleOptionStrings {
				def = "empty by default"
			}
			fmt.Fprintf(&b, "- Option `%s` (%s, %s): %s\n", o.Name, o.Kind, def, o.Summary)
		}
		if r.DocsAnchor != "" {
			fmt.Fprintf(&b, "- Details and examples: [checks](./checks.md#%s)\n", r.DocsAnchor)
		}
		b.WriteString("\n")
	}

	b.WriteString(`## Retired rule IDs

An audit is one rule with one ID. These IDs existed while 2.0 was in development, before the first release, and were merged into
the rule that reports their findings now. ` + "`-ignore`" + `, the ` + "`ignore`" + ` lists of ` + "`paths`" + ` and the ` + "`# jactionlint ignore=`" + ` comments still
take them: such an ignore matches only the findings that had the old ID, and jactionlint warns that the ID is deprecated.
` + "`rules`" + `, ` + "`ignores`" + `, ` + "`fix.rules`" + ` and ` + "`-rules`" + ` do not take them.

| Retired ID | Rule | Findings are on with |
| --- | --- | --- |
`)
	for _, rr := range jactionlint.RenamedRules() {
		on := "always"
		if rr.Option != "" {
			on = "the option `" + rr.Option + "`"
		}
		fmt.Fprintf(&b, "| `%s` | [%s](#%s) | %s |\n", rr.Old, rr.ID, rr.ID, on)
	}

	out := strings.TrimRight(b.String(), "\n") + "\n"
	_, err := io.WriteString(w, out)
	return err
}

func run(args []string, stdout io.Writer) error {
	check := false
	if len(args) > 0 && args[0] == "-check" {
		check = true
		args = args[1:]
	}
	if len(args) > 1 {
		return fmt.Errorf("usage: generate-rules-doc [-check] [dstfile|-]")
	}
	dst := "docs/rules.md"
	if len(args) == 1 {
		dst = args[0]
	}
	if check {
		// Compare with LF line endings so a Windows checkout with CRLF is not reported as stale.
		var want strings.Builder
		if err := generate(&want); err != nil {
			return err
		}
		got, err := os.ReadFile(dst)
		if err != nil {
			return err
		}
		if strings.ReplaceAll(string(got), "\r\n", "\n") != want.String() {
			return fmt.Errorf("%s is outdated. run \"mise run rules-doc\" (or \"go run ./scripts/generate-rules-doc\") and commit the result", dst)
		}
		return nil
	}
	if dst == "-" {
		return generate(stdout)
	}
	f, err := os.Create(dst)
	if err != nil {
		return err
	}
	if err := generate(f); err != nil {
		f.Close()
		return err
	}
	return f.Close()
}

func main() {
	if err := run(os.Args[1:], os.Stdout); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
