// Command generate-rules-doc generates docs/rules.md, the reference of all rule IDs, from the rule
// registry of the jactionlint package.
package main

import (
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/jdx/jactionlint/v2"
)

func levelText(s jactionlint.Severity) string {
	return s.String()
}

func profileText(p jactionlint.Profile) string {
	if p == "" {
		return "only when configured"
	}
	return string(p)
}

func yesNo(b bool) string {
	if b {
		return "yes"
	}
	return "no"
}

func generate(w io.Writer) error {
	var b strings.Builder
	b.WriteString(`<!-- Generated by scripts/generate-rules-doc from the rule registry. Do not edit by hand: run "go run ./scripts/generate-rules-doc". -->

# Rules

Every diagnostic of jactionlint has a stable ID such as ` + "`unpinned-uses`" + `. IDs are never renamed or reused, so they are safe to write in
[the configuration](./config.md), in [ignore comments](./usage.md#ignore-some-errors) and in CI annotations. The ID of a
finding is in the ` + "`id`" + ` field of ` + "`-format json`" + `, in the ` + "`ruleId`" + ` of ` + "`-format sarif`" + ` and in the output of ` + "`-rule-ids`" + `.

Each rule has:

- a **group**: ` + "`correctness`" + ` (mistakes which make a workflow fail or misbehave), ` + "`security`" + ` (insecure constructs), ` + "`policy`" + `
  (good practices which are not mistakes by themselves) or ` + "`style`" + `.
- a **default level**: ` + "`error`" + `, ` + "`warn`" + ` or ` + "`info`" + `. Only errors make jactionlint exit with status 1 unless ` + "`-strict-exit`" + ` is given.
- a **profile**: the first [profile](./config.md#profile) which enables the rule. ` + "`default`" + ` is used when no profile is configured, and
  ` + "`strict`" + ` and ` + "`all`" + ` include the rules of the profiles before them. Rules which no profile enables run only when the
  configuration turns them on.

` + "```yaml" + `
# .github/jactionlint.yaml
profile: strict
rules:
  unpinned-uses: warn # lower the level
  require-shell: off # turn a rule off
` + "```" + `

| ID | Group | Default level | Profile |
| --- | --- | --- | --- |
`)
	rules := jactionlint.Rules()
	for _, r := range rules {
		fmt.Fprintf(&b, "| [%s](#%s) | %s | %s | %s |\n", r.ID, r.ID, r.Group, levelText(r.DefaultLevel), profileText(r.Profile))
	}
	b.WriteString("\n")

	for _, r := range rules {
		fmt.Fprintf(&b, "## %s\n\n%s\n\n", r.ID, r.Summary)
		fmt.Fprintf(&b, "- Group: %s\n- Default level: %s\n- Profile: %s\n", r.Group, levelText(r.DefaultLevel), profileText(r.Profile))
		if r.Online {
			b.WriteString("- Needs network access: yes (only with `-online`)\n")
		}
		if r.Fixable {
			fmt.Fprintf(&b, "- Fixable: %s\n", yesNo(r.Fixable))
		}
		for _, o := range r.Options {
			def := "no default; the rule does nothing without it"
			if o.Default != nil {
				def = fmt.Sprintf("default %v", o.Default)
			}
			fmt.Fprintf(&b, "- Option `%s` (%s, %s): %s\n", o.Name, o.Kind, def, o.Summary)
		}
		if r.DocsAnchor != "" {
			fmt.Fprintf(&b, "- Details and examples: [checks](./checks.md#%s)\n", r.DocsAnchor)
		}
		b.WriteString("\n")
	}

	out := strings.TrimRight(b.String(), "\n") + "\n"
	_, err := io.WriteString(w, out)
	return err
}

func run(args []string, stdout io.Writer) error {
	if len(args) > 1 {
		return fmt.Errorf("usage: generate-rules-doc [dstfile|-]")
	}
	dst := "docs/rules.md"
	if len(args) == 1 {
		dst = args[0]
	}
	if dst == "-" {
		return generate(stdout)
	}
	f, err := os.Create(dst)
	if err != nil {
		return err
	}
	if err := generate(f); err != nil {
		f.Close()
		return err
	}
	return f.Close()
}

func main() {
	if err := run(os.Args[1:], os.Stdout); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
