package jactionlint

import (
	"regexp"
	"strings"
)

// Values of the "generated-files" key of the configuration.
const (
	// GeneratedFilesReport reports a generated file like any other file.
	GeneratedFilesReport = "report"
	// GeneratedFilesSkipPolicy does not report the rules of the policy and style groups in a generated file. It is the
	// default. The rules of the correctness and security groups still report.
	GeneratedFilesSkipPolicy = "skip-policy"
	// GeneratedFilesSkip reports nothing in a generated file.
	GeneratedFilesSkip = "skip"
)

// generatedHeaderRe matches the comment that tools put at the top of the files they write ("# This file was
// automatically generated by gh-aw. DO NOT EDIT.", "# generated by praktika", "# Generated by projen",
// "# Managed by modulesync - DO NOT EDIT").
var generatedHeaderRe = regexp.MustCompile(`(?i)\b(do not edit|do not modify|don'?t edit|(?:automatically |auto[- ]?)generated|generated (?:by|from|file)|managed by (?:modulesync|fullsend))\b`)

// generatedHeaderMaxLines bounds the search for the header: tools that write a file put the comment first, and a
// few put long metadata lines (gh-aw) before it.
const generatedHeaderMaxLines = 40

// isGeneratedSource reports whether the source starts with a comment that says that a tool wrote the file. Only the
// comment block at the top counts, before the first line of YAML: a "do not edit" in the middle of a workflow is
// about that line.
func isGeneratedSource(src []byte) bool {
	for i, line := range strings.Split(string(src[:min(len(src), 64<<10)]), "\n") {
		if i >= generatedHeaderMaxLines {
			return false
		}
		t := strings.TrimSpace(strings.TrimSuffix(line, "\r"))
		if t == "" || t == "---" {
			continue
		}
		if !strings.HasPrefix(t, "#") {
			return false
		}
		if generatedHeaderRe.MatchString(t) {
			return true
		}
	}
	return false
}

// dropForGeneratedFile removes the findings that nobody can act on in a file which a tool wrote, as the mode of
// "generated-files" says. The author fixes the generator, not the file.
func dropForGeneratedFile(errs []*Error, mode string) []*Error {
	switch mode {
	case GeneratedFilesReport:
		return errs
	case GeneratedFilesSkip:
		return nil
	}
	return filterErrs(errs, func(e *Error) bool {
		info, ok := LookupRule(e.ID)
		return !ok || (info.Group != RuleGroupPolicy && info.Group != RuleGroupStyle)
	})
}

func filterErrs(errs []*Error, keep func(*Error) bool) []*Error {
	ret := errs[:0:0]
	for _, e := range errs {
		if keep(e) {
			ret = append(ret, e)
		}
	}
	return ret
}
