package jactionlint

import (
	"regexp"
	"strings"
)

// Values of the "generated-files" key of the configuration.
const (
	// GeneratedFilesReport reports a generated file like any other file.
	GeneratedFilesReport = "report"
	// GeneratedFilesSkipPolicy does not report the rules of the policy and style groups in a generated file. It is the
	// default. The rules of the correctness and security groups still report.
	GeneratedFilesSkipPolicy = "skip-policy"
	// GeneratedFilesSkip reports nothing in a generated file.
	GeneratedFilesSkip = "skip"
)

// generatedHeaderRe matches a header comment that says that a tool wrote the file ("# This file was automatically
// generated by gh-aw. DO NOT EDIT.", "# generated by praktika", "# Generated by projen", "# Managed by modulesync - DO
// NOT EDIT", "# Code generated by x; DO NOT EDIT."). It is anchored at the start of the comment: the same words in the
// middle of a sentence are about something else ("# the matrix is generated from the list below").
var generatedHeaderRe = regexp.MustCompile(`(?i)^(?:(?:this|the) (?:file|workflow|configuration|config)\s+)?(?:(?:was|is|has been)\s+)?(?:code\s+)?(?:(?:automatically\s+|auto-?)generated|autogenerated|generated\s+(?:by|from|file|with|using)\b|managed\s+by\s+(?:modulesync|fullsend)\b)`)

// generatedByHandRe finds "generated by hand", which has the wording of a marker and the opposite meaning.
var generatedByHandRe = regexp.MustCompile(`(?i)generated\s+(?:by\s+(?:hand|a\s+human)|manually)\b`)

// doNotEditRe matches a comment which is only the marker, without a sentence about what not to edit: "DO NOT EDIT",
// "Do not edit this file.", "Please do not edit manually". A tool that writes "do not edit the matrix by hand" is a
// person talking about a part of a hand-written file.
var doNotEditRe = regexp.MustCompile(`(?i)^(?:please\s+)?(?:do\s+not|don'?t)\s+(?:edit|modify)(?:\s+(?:this\s+file|manually|directly|by\s+hand))*\W*$`)

// isGeneratedComment reports whether one comment line (with its "#") is a generated-file marker.
func isGeneratedComment(t string) bool {
	t = strings.TrimLeft(t, "# \t*-")
	if doNotEditRe.MatchString(t) {
		return true
	}
	return generatedHeaderRe.MatchString(t) && !generatedByHandRe.MatchString(t)
}

// generatedHeaderMaxLines bounds the search for the header: tools that write a file put the comment first, and a
// few put long metadata lines (gh-aw) before it.
const generatedHeaderMaxLines = 40

// isGeneratedSource reports whether the source starts with a comment that says that a tool wrote the file. Only the
// comment block at the top counts, before the first line of YAML: a "do not edit" in the middle of a workflow is
// about that line.
func isGeneratedSource(src []byte) bool {
	for i, line := range strings.Split(string(src[:min(len(src), 64<<10)]), "\n") {
		if i >= generatedHeaderMaxLines {
			return false
		}
		t := strings.TrimSpace(strings.TrimSuffix(line, "\r"))
		if t == "" || t == "---" {
			continue
		}
		if !strings.HasPrefix(t, "#") {
			return false
		}
		if isGeneratedComment(t) {
			return true
		}
	}
	return false
}

// dropForGeneratedFile removes the findings that nobody can act on in a file which a tool wrote, as the mode of
// "generated-files" says. The author fixes the generator, not the file.
func dropForGeneratedFile(errs []*Error, mode string) []*Error {
	switch mode {
	case GeneratedFilesReport:
		return errs
	case GeneratedFilesSkip:
		return nil
	}
	return filterErrs(errs, func(e *Error) bool {
		info, ok := LookupRule(e.ID)
		return !ok || (info.Group != RuleGroupPolicy && info.Group != RuleGroupStyle)
	})
}

func filterErrs(errs []*Error, keep func(*Error) bool) []*Error {
	ret := errs[:0:0]
	for _, e := range errs {
		if keep(e) {
			ret = append(ret, e)
		}
	}
	return ret
}
