package jactionlint

import (
	"slices"
	"strings"
	"testing"

	"github.com/google/go-cmp/cmp"
)

func TestIsGeneratedSource(t *testing.T) {
	tests := map[string]bool{
		"# This file was automatically generated by gh-aw. DO NOT EDIT.\nname: x\non: push\n":                                   true,
		"# gh-aw-metadata: {}\n# This file was automatically generated by gh-aw (v0.88.2). DO NOT EDIT. To debug\n#\nname: x\n": true,
		"# generated by praktika\nname: x\n":                          true,
		"# Generated by projen\nname: x\n":                            true,
		"# This file was autogenerated by dist: https://x\nname: x\n": true,
		"---\n# Managed by modulesync - DO NOT EDIT\nname: x\n":       true,
		"# AUTO-GENERATED, DO NOT EDIT!\nname: x\n":                   true,
		"name: x\n# DO NOT EDIT\non: push\n":                          false, // not in the comment at the top
		"# Build the project\nname: x\n":                              false,
		"# do not edit the matrix by hand\nname: x\n":                 true,
		"name: x\n": false,
		"":          false,
	}
	for src, want := range tests {
		if have := isGeneratedSource([]byte(src)); have != want {
			t.Errorf("%q: want %v but have %v", src, want, have)
		}
	}
}

func TestGeneratedFilesModes(t *testing.T) {
	// missing-permissions (policy) and template-injection (security)
	body := "name: x\non: push\njobs:\n  j:\n    runs-on: ubuntu-latest\n    steps:\n      - run: echo ${{ github.event.issue.title }}\n"
	gen := "# This file was automatically generated by gh-aw. DO NOT EDIT.\n" + body
	cfg := func(mode string) *Config {
		if mode == "" {
			return mustParseConfig(t, "profile: default\n")
		}
		return mustParseConfig(t, "profile: default\ngenerated-files: "+mode+"\n")
	}
	ids := func(src string, c *Config) []string {
		var ret []string
		for _, h := range lintZ(t, c, src) {
			ret = append(ret, h[strings.Index(h, " ")+1:])
		}
		return ret
	}
	hand := ids(body, cfg(""))
	if !slices.Contains(hand, "missing-permissions") || !slices.Contains(hand, "template-injection") {
		t.Fatalf("a hand written file reports both: %v", hand)
	}
	if diff := cmp.Diff([]string{"template-injection"}, ids(gen, cfg(""))); diff != "" {
		t.Errorf("default: policy rules are not reported in a generated file (-want +got): %s", diff)
	}
	if diff := cmp.Diff(hand, ids(gen, cfg("report"))); diff != "" {
		t.Errorf("report (-want +got): %s", diff)
	}
	if got := ids(gen, cfg("skip")); len(got) != 0 {
		t.Errorf("skip: %v", got)
	}
}
