# This file was generated by GoReleaser. DO NOT EDIT.
cask "jactionlint" do
  version "1.8.2"

  on_macos do
    on_arm do
      sha256 "de9eb05af3cde409dc0b37fe2fd6a21b875a575374e7b26c02d45a7086645c28"
      url "https://github.com/jdx/jactionlint/releases/download/v#{version}/jactionlint_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "42790b2565759b7f4a81696fb9034b2060f97f551d2ced54cf722c9de9abe6b2"
      url "https://github.com/jdx/jactionlint/releases/download/v#{version}/jactionlint_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "7d618749dbddd762a14bd491ea97bc4f6599626f830a11edc6c6522ead8bcd05"
      url "https://github.com/jdx/jactionlint/releases/download/v#{version}/jactionlint_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "6533bd8047fc012a3f66238d84f65cacdac669da00b9f6cf042c1734c252bc93"
      url "https://github.com/jdx/jactionlint/releases/download/v#{version}/jactionlint_#{version}_linux_amd64.tar.gz"
    end
  end

  name "jactionlint"
  desc "Static checker for GitHub Actions workflow files"
  homepage "https://github.com/jdx/jactionlint#readme"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "shellcheck",
    ]

  binary "jactionlint"
  manpage "man/jactionlint.1"

  # No zap stanza required
end
