# This file was generated by GoReleaser. DO NOT EDIT.
cask "jactionlint" do
  version "2.0.2"

  on_macos do
    on_arm do
      sha256 "1ad210bd21f4c70a81e0bffecc6d223daca8dd13e57fa6899787064f8b724c7c"
      url "https://github.com/jdx/jactionlint/releases/download/v#{version}/jactionlint_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "03ccb52f3bf3c6b1b6358689a4d31e5f05d558b32c0b8edaeac7c452abe7fff4"
      url "https://github.com/jdx/jactionlint/releases/download/v#{version}/jactionlint_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "978a9f32cc4ed1d81b94563fc49643b8b3a48dcba4d1ea089d9ba05f7e17e7a7"
      url "https://github.com/jdx/jactionlint/releases/download/v#{version}/jactionlint_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "026bce6d0ef196f5b22bf43acb1348d47c5d0a5ae61d6ec3bdba1229a823161b"
      url "https://github.com/jdx/jactionlint/releases/download/v#{version}/jactionlint_#{version}_linux_amd64.tar.gz"
    end
  end

  name "jactionlint"
  desc "Static checker for GitHub Actions workflow files"
  homepage "https://github.com/jdx/jactionlint#readme"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "shellcheck",
    ]

  binary "jactionlint"
  manpage "man/jactionlint.1"

  # No zap stanza required
end
