# This file was generated by GoReleaser. DO NOT EDIT.
cask "jactionlint" do
  version "2.1.0"

  on_macos do
    on_arm do
      sha256 "3766a4b0890d3eb36fe58760289885712131c7974de4bc9fabb9a3faa599e931"
      url "https://github.com/jdx/jactionlint/releases/download/v#{version}/jactionlint_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a88f2be76def62dd4fd9aed38c81d0db4144763012128a89800be80b1ee82e89"
      url "https://github.com/jdx/jactionlint/releases/download/v#{version}/jactionlint_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ec0c6496d8a2f37b2ae2a1af0fbf98d58df1f7c98a27cf9fdd64c20ad317234b"
      url "https://github.com/jdx/jactionlint/releases/download/v#{version}/jactionlint_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "baebfc5792135438fb3bb5ea266c3bf2538a089753616f1988ef618e4c0c3cb1"
      url "https://github.com/jdx/jactionlint/releases/download/v#{version}/jactionlint_#{version}_linux_amd64.tar.gz"
    end
  end

  name "jactionlint"
  desc "Static checker for GitHub Actions workflow files"
  homepage "https://github.com/jdx/jactionlint#readme"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "shellcheck",
    ]

  binary "jactionlint"
  manpage "man/jactionlint.1"

  # No zap stanza required
end
