name: Generate
on:
  push:
    paths:
      - 'scripts/generate-popular-actions/main.go'
      - 'scripts/generate-webhook-events/main.go'
    branches:
      - main
    tags-ignore:
      - '*'
  schedule:
    # Every Saturday 10:21 in JST
    - cron: '21 1 * * 6'
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  go-generate:
    if: ${{ github.repository == 'jdx/jactionlint' }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: '1.27'
          check-latest: true
      - name: Check new release on GitHub
        run: go run ./scripts/generate-popular-actions -d
      - run: go generate
      - run: |
          if git diff-files --quiet; then
            echo "pr=false" >> "$GITHUB_OUTPUT"
          else
            git diff
            echo "pr=true" >> "$GITHUB_OUTPUT"
          fi
        id: diff
      - uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          branch: 'ci/${{ github.run_id }}'
          commit-message: 'update generated files by `go generate` on CI'
          committer: 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'
          author: 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'
          title: 'Update generated files by CI'
          body: |
            This PR updates some generated files to the latest by running `go generate`.
            This PR was created by [this workflow run](https://github.com/jdx/jactionlint/actions/runs/${{ github.run_id }}) automatically.
            List of workflow runs is [here](https://github.com/jdx/jactionlint/actions/workflows/generate.yaml).
          assignees: jdx
        if: ${{ steps.diff.outputs.pr == 'true' }}
