name: Problem Matchers
on:
  push:
    paths:
      - 'scripts/generate-jactionlint-matcher/*.js'
      - 'testdata/examples/*.out'
      - 'testdata/err/*.out'
    branches:
      - main
    tags-ignore:
      - '*'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  matcher-test:
    name: Test generate-jactionlint-matcher
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false
      - uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4.3.0
      - name: Update test data
        run: mise run matcher:fixtures
      - name: Test jactionlint-matcher.json
        run: node ./scripts/generate-jactionlint-matcher/test.mjs
      - name: Ensure .github/jactionlint-matcher.json is up-to-date
        run: |
          mise run matcher
          if git diff --quiet; then
            echo 'OK'
          else
            echo 'ERROR! .github/jactionlint-matcher.json is outdated. Update it by "mise run matcher"' >&2
            set -x
            git diff
            exit 1
          fi
